GET http://localhost:8080/books
###

POST http://localhost:8080/books
Content-Type: application/json

{
    "id": "3",
    "title": "The Godfather",
    "author": "Mario Puzo"
}
###

DELETE http://localhost:8080/books/1