// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error)
	CreateUsers(ctx context.Context, arg CreateUsersParams) (User, error)
	DeleteNote(ctx context.Context, id int32) (Note, error)
	DeleteUser(ctx context.Context, id int32) (User, error)
	GetNote(ctx context.Context, id int32) (Note, error)
	GetUser(ctx context.Context, id int32) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserForUpdate(ctx context.Context, id int32) (User, error)
	ListNotes(ctx context.Context, arg ListNotesParams) ([]Note, error)
	ListNotesByUserId(ctx context.Context, arg ListNotesByUserIdParams) ([]Note, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserNotesCountPlusOne(ctx context.Context, id int32) (User, error)
}

var _ Querier = (*Queries)(nil)
