name: ci-test

on:
  push:
    branches: [ notesnotes-backend ]
  pull_request:
    branches: [ notesnotes-backend ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    
    - name: Checkout code into go module directory
      uses: actions/checkout@v2

    - name: Test
      run: make unit_test_run
